#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/new_post.sh --title "Post Title" [options]

Options:
  --title STRING        Required. Post title.
  --date YYYY-MM-DD     Optional. Defaults to today.
  --time HH:MM:SS       Optional. Defaults to current local time with :00 seconds.
  --slug STRING         Optional. Defaults to a slug derived from the title.
  --category STRING     Optional. Repeatable. Defaults to "Writing".
  --tag STRING          Optional. Repeatable. Defaults to "Draft".
  --image-file STRING   Optional. Defaults to "<slug>.png".
  -h, --help            Show this help.
EOF
}

escape_yaml() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g'
}

title=""
post_date="$(date '+%Y-%m-%d')"
post_time="$(date '+%H:%M:00')"
slug=""
image_file=""
categories=()
tags=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --title)
      title="${2:-}"
      shift 2
      ;;
    --date)
      post_date="${2:-}"
      shift 2
      ;;
    --time)
      post_time="${2:-}"
      shift 2
      ;;
    --slug)
      slug="${2:-}"
      shift 2
      ;;
    --category)
      categories+=("${2:-}")
      shift 2
      ;;
    --tag)
      tags+=("${2:-}")
      shift 2
      ;;
    --image-file)
      image_file="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$title" ]]; then
  echo "--title is required." >&2
  usage >&2
  exit 1
fi

if [[ -z "$slug" ]]; then
  slug="$(slugify "$title")"
fi

if [[ -z "$slug" ]]; then
  echo "Could not derive an ASCII slug from the title. Pass --slug explicitly." >&2
  exit 1
fi

if [[ ${#categories[@]} -eq 0 ]]; then
  categories=("Writing")
fi

if [[ ${#tags[@]} -eq 0 ]]; then
  tags=("Draft")
fi

if [[ -z "$image_file" ]]; then
  image_file="${slug}.png"
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
post_path="${repo_root}/_posts/${post_date}-${slug}.md"

if [[ -e "$post_path" ]]; then
  echo "Post already exists: $post_path" >&2
  exit 1
fi

{
  printf '%s\n' '---'
  printf '%s\n' 'layout: single'
  printf 'title: "%s"\n' "$(escape_yaml "$title")"
  printf 'date: %s %s +0800\n' "$post_date" "$post_time"
  printf '%s\n' 'categories:'
  for category in "${categories[@]}"; do
    printf '  - "%s"\n' "$(escape_yaml "$category")"
  done
  printf '%s\n' 'tags:'
  for tag in "${tags[@]}"; do
    printf '  - "%s"\n' "$(escape_yaml "$tag")"
  done
  printf '%s\n' '---'
  printf '\n'
  printf '![插图](/assets/images/misc_imgs/%s "Generated by OpenAI")\n' "$image_file"
  printf '\n'
  printf '%s\n' '<!-- Replace this placeholder with the final article body. -->'
} > "$post_path"

echo "Created $post_path"
echo "Expected image path: ${repo_root}/assets/images/misc_imgs/${image_file}"
